/* CVS $Id: $ */
package org.fit.burgetr.webstorm.ontology; 
import com.hp.hpl.jena.rdf.model.*;
import com.hp.hpl.jena.ontology.*;
 
/**
 * Vocabulary definitions from /home/burgetr/local/rdf/segmgen.owl 
 * @author Auto-generated by schemagen on 13 II 2014 14:21 
 */
public class Segm {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static OntModel m_model = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://www.fit.vutbr.cz/~imilicka/public/ontology/segmentation.owl#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    public static final ObjectProperty establishes = m_model.createObjectProperty( "http://www.fit.vutbr.cz/~imilicka/public/ontology/segmentation.owl#establishes" );
    
    public static final ObjectProperty isChildOf = m_model.createObjectProperty( "http://www.fit.vutbr.cz/~imilicka/public/ontology/segmentation.owl#isChildOf" );
    
    public static final DatatypeProperty backgroundColor = m_model.createDatatypeProperty( "http://www.fit.vutbr.cz/~imilicka/public/ontology/segmentation.owl#backgroundColor" );
    
    public static final DatatypeProperty fontFamily = m_model.createDatatypeProperty( "http://www.fit.vutbr.cz/~imilicka/public/ontology/segmentation.owl#fontFamily" );
    
    public static final DatatypeProperty fontSize = m_model.createDatatypeProperty( "http://www.fit.vutbr.cz/~imilicka/public/ontology/segmentation.owl#fontSize" );
    
    public static final DatatypeProperty fontStyle = m_model.createDatatypeProperty( "http://www.fit.vutbr.cz/~imilicka/public/ontology/segmentation.owl#fontStyle" );
    
    public static final DatatypeProperty fontWeight = m_model.createDatatypeProperty( "http://www.fit.vutbr.cz/~imilicka/public/ontology/segmentation.owl#fontWeight" );
    
    public static final DatatypeProperty hasChildren = m_model.createDatatypeProperty( "http://www.fit.vutbr.cz/~imilicka/public/ontology/segmentation.owl#hasChildren" );
    
    public static final DatatypeProperty textDecoration = m_model.createDatatypeProperty( "http://www.fit.vutbr.cz/~imilicka/public/ontology/segmentation.owl#textDecoration" );
    
    public static final OntClass Area = m_model.createClass( "http://www.fit.vutbr.cz/~imilicka/public/ontology/segmentation.owl#Area" );
    
}
